### PR TITLE
Add-ocl-header

### PR DESCRIPTION
**Pull request by StRigaud**
This PR should fix the need to have the OpenCL headers in the system path for build. See https://github.com/clEsperanto/clesperantoj_prototype/issues/28#issuecomment-2133919872

We fetch the headers from github and stores them in a controlled path that we can include later on for the Jar build.

### CODE REVIEW

**Comment by StRigaud** [comment]
@carlosuc3m 

Headers are now directly dl and set in the `./lib/{os}/include` folder. This should solve the last part for stabilizing the maven build.
If you have time to test it on you Windows to confirm you do not need to manage the `INCLUDE` environment variable.

**Comment by carlosuc3m** [comment]
does this mean that we do not need to do `apt install ocl-icd-opencl-dev` anymore on Linux systems?

**Comment by carlosuc3m** [comment]
It works well on windows by the way!

**Comment by StRigaud** [comment]
> does this mean that we do not need to do apt install ocl-icd-opencl-dev anymore on Linux systems?

Normally yes! The package install the `.so` dynamic library already provided by your drivers install (CUDAToolkit, etc.), and the headers. You needed it because you did not have the headers in your PATH which are needed for build (not deployment).

Now, with the PR, the headers are fetch from the khronos repo and included with the `pom.xml`.

If it works for windows, I will merge this then!

**Pull request merged**
