### PR TITLE
Add missing types for ImageJ

### PR DESCRIPTION
**Pull request by carlosuc3m**
This pull request was created from [branch](https://github.com/clEsperanto/clesperantoj_prototype/pull/49), so that needs to happens first.
This addresses https://github.com/clEsperanto/clesperantoj_prototype/issues/60

### CODE REVIEW

**Comment by carlosuc3m** [comment]
This pull request adds the missing data types int8, int16, int32 and uint32 to the imageplus converter.

It also contains the corresponding push and pull tests for imageplus.
@StRigaud

**Comment by StRigaud** [comment]
No more error on my side after a quick test running this:
https://github.com/clEsperanto/clij3/blob/a0b80e70ad2a3ab59047d4af8783a1885915cfde/src/main/java/net/clesperanto/test/YetAnotherPlayground.java#L12-L31

I have the correct output.

Simple question though is it normal the output is of type `8-bit` for FIJI ?

**Comment by StRigaud** [comment]
my bad, the return is 32-bit

**Comment by carlosuc3m** [comment]
One remark is that the tests might fail at some point if many actions are running in parallel and the runners run out of memory.

**Pull request merged**
