### PR TITLE
Create a Github Action that builds the JAR file in every OS

### PR DESCRIPTION
**Pull request by carlosuc3m**
Create a Github action that creates the JAR file for Windows, Ubuntu and Macos-13.

The JAr file for MacOS-14 (Apple Silicon) can also be created but the RAM provided is more limited and it takes quite long.

Some comments about the action itself:

- [Increase swap on Ubuntu](https://github.com/clEsperanto/clesperantoj_prototype/blob/fea9c18750b5e3aa8d02d2929890bcdec33e7b1c/.github/workflows/build.yaml#L47) : the Github action stopped because it run out of resources (error 143), in order to avoid this, the swap is increased and it does not fail anymore.

- OpenCl runtime on Ubuntu is required to be installed. On Linux did it with `sudo apt install ocl-icd-opencl-dev` and on Windows, i copied what is done [here](https://github.com/clEsperanto/CLIc/blob/39e8f92ae091ca023313e35b437061d51de89877/.github/workflows/build-test.yml#L58).

```
      - name: Install ocl-icd-loader - windows
        if: matrix.os == 'windows-latest'
        run: |
          cd ..
          git clone --branch ${{ env.opencl-icd-loader-git-tag }} https://github.com/KhronosGroup/OpenCL-ICD-Loader
          git clone --branch ${{ env.opencl-headers-git-tag }} https://github.com/KhronosGroup/OpenCL-Headers
          # cmake -D CMAKE_INSTALL_PREFIX="./OpenCL-Headers/install" -S "./OpenCL-Headers" -B "./OpenCL-Headers/build"
          cmake -S "./OpenCL-Headers" -B "./OpenCL-Headers/build"
          cmake --build "./OpenCL-Headers/build" --parallel 6 --target install
          cmake -D CMAKE_PREFIX_PATH="./OpenCL-Headers" -D OPENCL_ICD_LOADER_HEADERS_DIR="./OpenCL-Headers/" -S "./OpenCL-ICD-Loader" -B "./OpenCL-ICD-Loader/build" -A x64
          cmake --build "./OpenCL-ICD-Loader/build" --parallel 6 --target install --config Release
        shell: bash -l {0}
```

Sorry if any of this is redundant, but i am still trying to wrap my head around what are the differences between the runtime, the icd loader.....

Finally, instead of defining the OS in such detail as in [here](https://github.com/clEsperanto/CLIc/blob/39e8f92ae091ca023313e35b437061d51de89877/.github/workflows/build-test.yml#L22), I used the deafault configurations of the runners and installed MVSC compiler environment. I did it this way for simplicity but it might be better to define the configuration of the runners more in detail.

This branch also includes https://github.com/clEsperanto/clesperantoj_prototype/pull/32 and https://github.com/clEsperanto/clesperantoj_prototype/pull/30

### CODE REVIEW

**Comment by StRigaud** [comment]
> [Increase swap on Ubuntu](https://github.com/clEsperanto/clesperantoj_prototype/blob/fea9c18750b5e3aa8d02d2929890bcdec33e7b1c/.github/workflows/build.yaml#L47) : the Github action stopped because it run out of resources (error 143), in order to avoid this, the swap is increased and it does not fail anymore.

never encountered this... great that we have a solution!

> Sorry if any of this is redundant, but i am still trying to wrap my head around what are the differences between the runtime, the icd loader.....

I still mixup things about this, so no worries. This is the correct way to do. All good.

> Finally, instead of defining the OS in such detail as in [here](https://github.com/clEsperanto/CLIc/blob/39e8f92ae091ca023313e35b437061d51de89877/.github/workflows/build-test.yml#L22), I used the deafault configurations of the runners and installed MVSC compiler environment. I did it this way for simplicity but it might be better to define the configuration of the runners more in detail.

I tend to avoid github-actions not maintained by github or large official entities (like pipy, microsoft, etc.). They can easily fail to maintain the actions which, follow up on a github update or change, make you CI fail. Lets keep it this way for now but on the long run we may need to update it for a more heavy yet stable approach.

**Comment by StRigaud** [comment]
Quick adds up: 

You may want to look at the `upload-artifact` and `download-artifact` github action. They allows you to upload files into a storage and retrieve them later

If you look on the pyclesperanto deploy CI for example: https://github.com/clEsperanto/pyclesperanto/actions/runs/9552215119
at the bottom of the page you can see the `artifacts` section which are the output wheel package uploaded at the end of the CI, We can do the same for the JAR with the `upload-artifact`

the `download-artifacts` can then be used in an other CI later for reusing these artifact (JAR) (for upload to maven scijava for example)

**Comment by carlosuc3m** [comment]
Great! Should I merge already?

Or should we also prepare the Action for deployment now?

Also with respect to deploying the JAR file, there are two options. We can have 3 (or 4) separate versions of the JAR, one for linux, one for windows and one for mac (and maybe one for mac arm64) so the user just needs to download the binaries for their OS, or put all the binaries in one heavier JAR and distribute that one for everyone.

The second approach might be better for end user applications such as Fiji where the dependency management is done with the Fiji update site.

**Comment by StRigaud** [comment]
You can merge!

Let's keep deployment for when we have actually something to deploy, and a strategy behind it (Fiji update, maven scijava, github, etc.)

**Pull request merged**
