### PR TITLE
Add utilitary methods to convert back and forth to Javacpp objects

### PR DESCRIPTION
**Pull request by carlosuc3m**
I have created several methods that can be used to convert to ArrayList the `Vector` objects created by Javacpp.

HOwever I am finding an issue here. FloatVector and ArrayJVector will not be available until the presets that generate the corresponding class are present. THat is first we need to autogenerate all the javacpp code and then we can use FloatVector and ArrayJVector.

@StRigaud

### CODE REVIEW

**Comment by StRigaud** [comment]
Does this means changing the pom or the build order?

**Comment by carlosuc3m** [comment]
Nope, it means that we need to add the code for all the tiers first to know which objects we have to deal with.

**Comment by StRigaud** [comment]
I am fighting with the unordered_map and making some tests. I will soon push here the tiers and we can build up from there

**Comment by carlosuc3m** [comment]
Awesome thanks!

**Comment by StRigaud** [comment]
I had to bump up the javacpp version in order to properly do a mapping of the `unordered_map`.

I push the auto-gen tiers this afternoon

**Comment by StRigaud** [comment]
I had to make some minor change in the c++ code (clEsperanto/CLIc#329) that still need to be confirmed and add some minor fix to the gencle (like `bool` become `boolean` in java ...) but it works :tada: 

@carlosuc3m I let you have a look and feel free to add or modify what you think is needed!

We are now missing a few tests and to clean up a bit !

**Comment by carlosuc3m** [comment]
Everything looks good to me.
Is this enough for the autogeneration?
@StRigaud

**Pull request merged**
