### PR TITLE
ImagePlus convertion not working

### PR DESCRIPTION
**Pull request by StRigaud**
The converter between ArrayJ and ImagePlus does not seems to work correctly.

I have an issue with a wrong bitdepth provided during the convertion `ArrayJ` to `ImagePlus`, most likely because of this:
https://github.com/clEsperanto/clesperantoj_prototype/blob/f82b508d50c53f330b97d189a7ee5e48d1a0c569/src/main/java/net/clesperanto/imagej/ImageJDataType.java#L71-L73
which return the enum int (2 for float) instead of the bitdepth required for `IJ.createImage()`

But I think there is an other issue as the even if I try with the correct bitdepth, the output ImagePlus from `ImageJcopyArrayJtoImgLib2()` seems empty.

### CODE REVIEW

**Comment by StRigaud** [comment]
`ImageJConverters.copyImgLib2ToArrayJ()` seems to create a new ArrayJ of dimensions (1,1,1)

**Comment by StRigaud** [comment]
I was able to take an image from Fiji, push it, run absolute, and pull it witht the correct output.
I only tested for a stack (3D image), I did not tested the behaviour with `channel` or `time` nor with 2d or 1d but hopefully they works

@carlosuc3m can you check if the correction I did make sense? Don't hesitate to add some extra correction if needed.

**Comment by StRigaud** [comment]
@carlosuc3m maybe necessary to test the Icy converter too for similar issues.

**Comment by carlosuc3m** [comment]
HEllo @StRigaud 
The changes are great!

THe only thing is that I think it would be great to maintain a naming consistency across all the converters data types. For ImageJConverter it would mean getting rid of one of the two methods `createDAtaType` or `getBitDepth` and  rename teh method to something that makes sense across every DAtaType class

**Pull request merged**
